[workspace]
members = ["moonstone", "moonstone_macro"]
resolver = "3"


[workspace.dependencies]
godot = "0.4.2"
syn = "2.0.106"
quote = "1.0.40"
proc-macro2 = "1.0.101"
paste = "1.0.15"
heck = "0.5.0"
replace_with = "0.1.8"
slotmap = "1.0.7"
ahash = "0.8.12"
parking_lot = "0.12.5"
