[package]
name = "moonstone"
version = "0.1.0"
edition = "2024"

[dependencies]
godot = { workspace = true }
moonstone_macro = { path = "../moonstone_macro" }
parking_lot = { workspace = true }
paste = { workspace = true }
